Multas/Multas/Models/Agentes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Multas.Models {
    public class Agentes {

        public Agentes() {
            ListaMultas = new HashSet<Multas>();
        }

        // id, nome, esquadra, foto


        public int ID { get; set; }
        [Required(ErrorMessage = "Por favor, insira o nome do agente.")]
        //validar um nome
        //letras, formando palavras
        //letras isoladas, em alguns casos. ex:e, de, do, dos, etc.
        //espaço em branco entre palavras 
        //uso de simbolos especiais. ex: letras acedelhadas, -, '
        // \d{4}-\{3}\w* - indicação para o código postal
        //[]- identifica conjunto
        //() - agrupamentos, juntam um conjunto de regras
        //+ - quanrificador : 1 ou mais
        //* - quantificador : 1  ou mais
        //? -quantufucador: 0 ou 1
        //()+ o agrupamento ira acontecer um ou mais vezes 
        //()* o agrupamento ira acontecer as vezes que o utilizador desejar
        //{i} quantificador: indica que são exatamente i valores 
        //{i,j} quantificador: indica que são exatamente entre i e j valores
        // | - seprara opções de escolha
        [RegularExpression("([A-ZÁÉÍÓÚa-záéíóúàèìòùãõâêîôûäëïöüçñ]+( |-|')?)+", ErrorMessage = "Só pode escrever letras no Nome. Deve começar por uma maiúcula ")]

        //(((((e|de|da|do|das|dos) )?)|-|')+[A-ZÁÉÍÓÚ][a-záéíóúàèìòùãõâêîôûäëïöüçñ]+){2,3}
        public string Nome { get; set; }
        [Required(ErrorMessage = "Por favor, insira a esquadra onde o agente trabalha.")]
       // [RegularExpression ("Tomar|Ourém|Lisboa|Leiria|Alcanena|Torres Novas")]
        public string Esquadra { get; set; }
        
        public string Fotografia { get; set; }

        //identifica as multas passadas pelo Agente
        //o virtual vai "dizer" para associar as multas ao agente
        public virtual ICollection<Multas> ListaMultas { get; set; }

        //*********************************************************************************
        //adicionar uma chave forasteira para a tabela da autenticação 
        [Required]
        public string UserNameId { get; set; }



    }
}

Multas/Multas/Controllers/AgentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Multas.Models;

namespace Multas.Controllers


{
    [Authorize]//só as pessoas autenticadas podem executar estas tarefas 
    public class AgentesController : Controller
    {
        //cria uma variavel que representa a base de dados
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Agentes
        //a anotação seguinte obriga a pelo menos um dos Roles 
        [Authorize(Roles ="RecursosHumanos, Agente")] //só os agentes e as pessoas 
        //dos recursos humanos acedem a esta listagem
        //
        //assim, obrigatoriamente tem de ter os dois roles 
        //[Authorize(Roles ="Agente")]
        //[Authorize(Roles ="RecursosHumanos")]
        public ActionResult Index()
        {
            //procura a totalidade dos agente na base de dados 
            //Intrução feita em LINQ
            //SELECT * from Agentes ORDER BY name
            var listaAgentes = db.Agentes.OrderBy(a=>a.Nome).ToList();

            if (!User.IsInRole("RecursosHumanos")) {
                //o utilizador NÃO pertence aos 'recursos humanos'
                //preciso de saber o ID do Agente que está autenticado 
                //como?

                //SELECT FROM Agentes WHERE UserNameId = UserName da pessoa autenticada 
                int idAgente = db.Agentes
                    //identificar o agente
                    .Where(a=>a.UserNameId == User.Identity.Name)
                    .FirstOrDefault()
                    .ID;




                return RedirectToAction("Details", new {id=idAgente});





            }
            return View(listaAgentes);
        }

        // GET: Agentes/Details/5
        /// <summary>
        /// Mostra os dados de um Agente 
        /// </summary>
        /// <param name="id">identifica o Agente</param>
        /// <returns>Devolve a View com os dados</returns>
        /// int? - pode nao ser preenchido
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //resposta por defeito
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                //este erro ocorre pois o utilizador anda a "fazer asneiras"
                return RedirectToAction("Index");

            }
            //SELECT * FROM Agentes WHERE ID=id
            Agentes agente = db.Agentes.Find(id);
            //o Agente foi encontrado?
            if (agente == null)
            {
                //O Agente não foi encontrado, porque o utilizador está 'à pesca'
                return RedirectToAction("Index");
            }
            //o Agente foi encontrado.
            //posso mostrar os seus dados a quem os solicitou?
            //sim, e
            //  - o utilizador pertence ao role 'recursos humanos' ou
            //  - o utilizador pertence ao role 'gestão de multas' ou
            //  -é o utilizador autenticado 
            if (User.IsInRole("RecursosHumanos") ||
                    User.IsInRole("GestorMultas") ||
                    agente.UserNameId == User.Identity.Name
                    )
            {
                //enviar para a View os dados do Agente que foi procurado e encontrado 
                return View(agente);


            }
            else {



            }









            return View(agente);
        }

        // GET: Agentes/Create
        //a anotação seguinte obriga a ter o role Recursos Humanos
        [Authorize(Roles = "RecursosHumanos")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Agentes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// criação de um novo agente
        /// </summary>
        /// <param name="agente"> recolhe os dados do Nome e da Esquadra do Agente</param>
        /// <param name="fotografia">representa a fotografia que identifica o Agente</param>
        /// <returns>devolve uma View</returns>
        [HttpPost]
        //anotação para proteger o código de ataques 
        [ValidateAntiForgeryToken]
        //a anotação seguinte obriga a ter o role Recursos Humanos
        [Authorize(Roles = "RecursosHumanos")]
        public ActionResult Create([Bind(Include = "Nome,Esquadra")] Agentes agente,
                                          HttpPostedFileBase fotografia)
        {
            //precisamos de processar a fotografia
            //1º será que foi fornecido um ficheiro?
            //2º será do tipo correto (jpg, png)?
            //3º se for do tipo correto, guarda-se 
            //      se não for, atribui-se um 'avatar genérico' ao utilizador

            //var auxiliar 
            string caminho = "";
            bool haFicheiro = false;
            //há ficheiro?
            if (fotografia == null)
            {
                //não ha ficheiro
                //atribui-se-lhe o avatar 
                agente.Fotografia = "noUser.jpg";
            }
            else {
                //há ficheiro
                //é correto?
                if (fotografia.ContentType == "image/jpeg" || fotografia.ContentType == "image/png") {
                    //estamos perante uma fotografia correta 
                    string extensao = Path.GetExtension(fotografia.FileName).ToLower();
                    Guid g;
                    g = Guid.NewGuid();
                    //nome do ficheiro
                    string nome = g.ToString() + extensao;
                    //onde guardar o ficheiro 
                    //MapPath vai a raiz do projeto e avança até a pasta das imagens
                    //Combine - junta a string com o nome do ficheiro
                     caminho = Path.Combine(Server.MapPath("~/imagens"), nome);

                    //atribuir ao agente o nome do ficheiro
                    agente.Fotografia = nome;

                    //assinalar que ha fotografia
                    haFicheiro = true;
                }
            }   
            //verifica se os dados fornecidos estão de acordo com as regras definidas no Modelo
            if (ModelState.IsValid)
            {
                //sempre que se interage com a base de dados é necessário colocar um try/catch
                try
                {
                    //adição de um novo agente
                    db.Agentes.Add(agente);
                    //"commit" - consolida os dados na BD
                    db.SaveChanges();
                    //vou guardar o ficheiro 
                    if(haFicheiro)
                    fotografia.SaveAs(caminho);
                
                    //devolve o controlo para a página do index
                    return RedirectToAction("Index");

                }
                catch (Exception) {
                    ModelState.AddModelError("", "Ocorreu um erro com a escrita de dados do novo Agente");
                }
                
            }
            //caso nao seja válido
            return View(agente);
        }

        // GET: Agentes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Agentes agente = db.Agentes.Find(id);
            if (agente == null)
            {
                return RedirectToAction("Index");
            }
            return View(agente);
        }

        // POST: Agentes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Esquadra,Fotografia")] Agentes agente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agente);
        }

        // GET: Agentes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Agentes agente = db.Agentes.Find(id);
            if (agente == null)
            {
                return RedirectToAction("Index");
            }
            //o agente foi encontrado 
            //vou salvaguardar os dados para posterior validação
            //- guardar o ID do Agente num cookie cifrado - vai para o cliente 
            //- guardar o ID numa variável de sessão - uma variável de sessão nunca vai para o cliente fica sempre no servidor
            //    (se se usar o ASP .NET Core, esta ferramenta já não existe
            //- outras alternativas válidas 
            Session["Agente"] = agente.ID;
            //mostra na view os dados do agente
            return View(agente);
        }

        // POST: Agentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null) {
                return RedirectToAction("Index");
            }
            //o ID não é nulo 
            //Será o ID o que eu espero?
            //vamos validar se o ID está correto
            if (id != (int) Session["Agente"]) {
                return RedirectToAction("Index");
            }



            //procura o agente a remover
            Agentes agente = db.Agentes.Find(id);

            if (agente == null) {
                //não foi encontrado o agente 
                return RedirectToAction("Index");
            }

Multas/Multas/Views/Agentes/Create.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Adicionar um Agente";
}

<h2>Create</h2>


@using (Html.BeginForm("Create",
                        "Agentes",
                        FormMethod.Post,
                        @*esta intrução permite enviar o ficheiro para o servidor*@
                        new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agentes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Esquadra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Esquadra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Esquadra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*permite a introdução dos dados da fotografia do Agente*@
                @*o name serve para conseguirmos aceder a este input através do controller*@
                <input type="file"  accept=".jpg"  name="fotografia/>                                                                                                                                           " />

                @*textbox pra introduzir o nome da fotografia
        @Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Agentes", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Multas/Multas/Views/Agentes/Delete.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Delete";
}

<h2>Remover</h2>

<h3>Quer remover este agente?</h3>
<div>
    @*este helper mostra as mensagens de erro que existem associadas ao Modelo*@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <h4>Agentes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Esquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Esquadra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Fotografia)*@

            <img src="~/imagens/@Model.Fotografia" height="150" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Lista de Agentes", "Index")
        </div>
    }
</div>

Multas/Multas/Views/Agentes/Details.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes do Agente <i>@Model.Nome</i></h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Esquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Esquadra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>

        <dd>
            <img src="~/imagens/@Model.Fotografia" height="150" />
            @*@Html.DisplayFor(model => model.Fotografia)*@
        </dd>

</dl>

    @*mostrar os dados das multas emitidas pelo Agente*@
    <hr /> 
    <h4>Lista das Multas</h4>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.ListaMultas.FirstOrDefault().ID)</th>
            <th>@Html.DisplayNameFor(model => model.ListaMultas.FirstOrDefault().DataDaMulta) </th>
            <th>@Html.DisplayNameFor(model => model.ListaMultas.FirstOrDefault().LocalDaMulta)</th>
            <th>Condutor</th>
            <th>Viatura</th>
        </tr>
        @*listar as multas de um agente*@>
        @foreach (var multa in Model.ListaMultas)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => multa.ID)</td>
            <td>@*equivale ao de cima*@ @multa.DataDaMulta</td>
            <td>@multa.LocalDaMulta</td>
            <td>
                @*link para o condutor*@
                @*condutor*@
                <a href="/condutores/details/@multa.Condutor.ID">@multa.Condutor.Nome</a>
            </td>
            <td>
                @*link para a viatura*@
                @*viatura*@
                @*faz o mesmo que <a href="/condutores/details/@multa.Viatura.ID">@multa.Viatura.Matricula</a>*@
                @Html.ActionLink(multa.Viatura.Matricula,
                                "Details",
                                "Viaturas",
                                new { id = multa.Viatura.ID},
                                null)
            </td>

        </tr>

        }

    </table>
    <hr />
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Lista de Agentes", "Index")
</p>

Multas/Multas/Views/Agentes/Edit.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agentes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Esquadra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Esquadra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Esquadra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Agentes", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Multas/Multas/Views/Agentes/Index.cshtml
@model IEnumerable<Multas.Models.Agentes>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Agentes</h2>

@if (User.IsInRole("RecursosHumanos"))
{
<p>
    @Html.ActionLink("Criar novo agente", "Create")
</p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
            @**helper que está a interagir com a base de dados -- (quando acaba com "for")
                helper que mostra o nome do atributo*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Esquadra)
        </th>
        <th>
            
                
                @Html.DisplayNameFor(model => model.Fotografia)
           
         
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    @*item - objeto do tipo de agentes*@
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Esquadra)
        </td>
        <td>
            @*
                mostra o conteudo do campo fotografia
                @Html.DisplayFor(modelItem => item.Fotografia)
            *@

            @*mostrar a imagem do agente*@
            @*concatnação de um texto que é comum com um dinamico*@
            <img src="~/imagens/@item.Fotografia"  height="50"/>
        </td>
        <td>
            @Html.ActionLink("Detalhes", "Details", new { id = item.ID }) 

            @if (User.IsInRole("RecursosHumanos")){
            <text>

                @Html.ActionLink("Editar", "Edit", new { id = item.ID })
                |
                @Html.ActionLink("Remover", "Delete", new { id = item.ID })
                |
            </text>

             }

        </td>
    </tr>
}

</table>